### ISSUE TITLE
”issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by thike33** [thike33/code_sheet#32]
### 概要
issue作成のレビューをしていただくためのissueです。
MVPリリース時の機能・本リリース時の機能・必要なページが記載されています。

[CodeSheet開発プロジェクト](https://github.com/users/thike33/projects/13)

### MVPリリース時
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 投稿機能
- [x] 投稿一覧機能
- [x] 投稿詳細機能
- [x] 投稿編集機能
- [x] 投稿削除機能
- [x] ユーザーの投稿一覧機能
- [x] マイページ機能
- [x] マイページ編集機能
- [x] コードのハイライト機能

### 本リリース時
- [x] ユーザー登録(Googleアカウント)
- [x] コードの公開・非公開機能
- [x] いいね機能
- [x] ブックマーク機能
- [x] マルチ検索・オートコンプリート機能
- [x] カテゴリー検索機能
- [x] パスワード再設定機能
- [x] ライブラリ対応機能（jQueryやSwiperなど）
- [x] APIを通して保存したコードを返す機能

### 必要なページ
- [x] トップページ
- [x] ユーザー登録
- [x] ログインページ
- [x] 新規投稿ページ
- [x] 投稿一覧ページ
- [x] 投稿編集ページ
- [x] 投稿詳細ページ
- [x] マイページ
- [x] マイページ編集
- [x] ユーザー投稿一覧ページ
- [x] ブックマーク一覧ページ
- [x] パスワード再設定発行ページ
- [x] パスワード再設定ページ
- [x] 利用規約ページ
- [x] プライバシーポリシーページ
- [x] お問い合わせページ

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
画像投稿の際に画像の保存はどうするか決めておられますか？

もし、デプロイ時の対応を検討されていない場合は下記URLを参考に検討してみてください！

URL：https://pikawaka.com/rails/carrierwave

**Comment by tmtkzk0823** [comment]
確認しました。
概ねいいと思います！
LGTMです！

**Comment by thike33** [comment]
ありがとうございます！
